sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t josephmargen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true josephmargen/react-test npm test

after_success:
  - travis_wait 30 docker build -t josephmargen/multi-client ./client
  - travis_wait 30 docker build -t josephmargen/multi-nginx ./nginx
  - travis_wait 30 docker build -t josephmargen/multi-server ./server
  - travis_wait 30 docker build -t josephmargen/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - travis_wait 30 docker push josephmargen/multi-client
  - travis_wait 30 docker push josephmargen/multi-nginx
  - travis_wait 30 docker push josephmargen/multi-server
  - travis_wait 30 docker push josephmargen/multi-worker
